### PR TITLE
Initial design of Github Portfolio

### PR DESCRIPTION
**Pull request by AABoyles**
Based on https://cdcgov.github.io/MEBT

### CODE REVIEW

**Comment by AABoyles** [comment]
Can be viewed live at https://aaboyles.github.io/cdcgov.github.io/

**Comment by leebrian** [comment]
This is awesome. Can now be viewed live at https://cdcgov.github.io

I like this look and feel, what's the most convenient place for me to ask questions. Can I make you a contributor to cdcgov.github.io's repo so you can see issues and such?

I like how you added instructions for groups who want a custom image. Is it really autorebuilding on merge? What do we need to set up to automate the build?

**Comment by AABoyles** [comment]
Please do as me as a contributor--I'll be able to help manage merge requests on the of chance we get a bunch of traffic from people with images 😁.

There's no build process! There's a cached JSON file with the details of CDC projects from the GitHub API, but there's also an API call to GitHub to make sure it's still fresh. If not, the repo data gets updated. I'm sure there are bugs in the logic, but once we figure out and squish them, the repo should never need to be updated and the website should stay fresh anyway.

**Comment by leebrian** [comment]
Thanks. Added you as contributor.

How do I regenerate the projects.json file? My image got picked up for opencdc, but it looks like the description is still static from when the projects.json file was generated.

**Comment by AABoyles** [comment]
The aforementioned bugs begin to rear their ugly heads! The description should come from the API if it's been updated. I'll take a look, see issue # 1

**Pull request merged**
